### ISSUE TITLE
 Issue in sending Baicoin to another wallet

### ISSUE THREAD

**Issue by squidtime** [tharindupr/BaiCoin#13]
Hi Team

when I try to send Baicoin to another user wallet it fails with "Account has insufficient funds" error,  but both getinfo and getbalance show account has enough Baicoin for the transaction. 

`root@lubuntu:~/BaiCoin/bin# ./baicoind getinfo`
`{
    "version" : 80705,
    "protocolversion" : 70002,
    "walletversion" : 60000,
    "balance" : 21.99910000,
    "blocks" : 11127,
    "timeoffset" : 0,
    "connections" : 12,
    "proxy" : "",
    "difficulty" : 0.04120244,
    "testnet" : false,
    "keypoololdest" : 1621967526,
    "keypoolsize" : 203,
    "paytxfee" : 0.00000000,
    "mininput" : 0.00001000,
    "errors" : ""
}`

`root@lubuntu:~/BaiCoin/bin# ./baicoind getbalance`
`21.99910000`

When I try to send Baicoin, transaction failed with below message, tried with different amounts ranging from 1 to 10
 
`root@lubuntu:~/BaiCoin/bin# ./baicoind sendfrom sam BRDzK3ToR3ivnAAhwaVJf8Fu4J7DubfDcf 10`
`error: {"code":-6,"message":"Account has insufficient funds"}`

**Comment by tdevinda** [comment]
@tharindupr Will you check on this?

**Comment by keshan** [comment]
Hey @squidtime  Can you try sendtoaddress instead?

This may be also helpful : https://bitcointalk.org/index.php?topic=141429.0

**Comment by squidtime** [comment]
@keshan Thanks. yeah sendtoaddress  worked. 

But while further investigating noticed that the block reward is in an account with empty name. So using sendfrom  I had tried to send from an account(sam)  with negative balance 

`root@lubuntu:~/BaiCoin/bin# ./baicoind listaccounts`

`{
    "" : 22.00000000,
    "sam" : -0.00090000
}
`
