### ISSUE TITLE
Any other toyyo having a issue using this?

### ISSUE THREAD

**Issue by Wishmitha** [tharindupr/BaiCoin#14]
I didn't even try just want to make sure.

**Comment by IsuraManchanayake** [comment]
Can build for us baiyas

**Comment by Wishmitha** [comment]
> Can use for us baiyas

Feedback from some Jeppos would be helpful too

**Comment by teshanshanuka** [comment]
Can confirm that it works.I just mined a few coins just for fun (Had to use a docker since I am running Ubuntu 20) Looking forward to buy a piece of land from the port city in the future

**Comment by teshanshanuka** [comment]
[Here](https://gist.github.com/teshanshanuka/3471b2916f36f1450861fbbd24f43cce)'s the Dockerfile if anyone needs

**Comment by keshan** [comment]
@teshanshanuka this is great! if you don't mind, can you make a PR to the original repo with the DOCKERFILE. Thanks!

**Comment by tdevinda** [comment]
Nice terminology. People who cannot use this, or are having an issue (building, installing etc.) should hereafter be labelled ```Toiya```.
