### ISSUE TITLE
baicoin-qt: cannot connect to X server 

### ISSUE THREAD

**Issue by NavodBK** [tharindupr/BaiCoin#20]
I'm running baicoin miner with docker because I'm using ubuntu 20. Mining works fine but I'm getting error
`baicoin-qt: cannot connect to X server `
when trying to run the wallet application. (`bin# ./baicoin-qt`)
Does anyone know a method to solve this?

**Comment by tharindupr** [comment]
You cannot run the wallet GUI application inside a docker. GUI wallet is only supported on Ubuntu 18. But you have all the wallet functionalities on the CLI version. 

Try  `./baicoind help ` to list all the available commands.

**Comment by NavodBK** [comment]
Great! Thanks for the clarification.
