### ISSUE TITLE
Requesting to add discussion support

### ISSUE THREAD

**Issue by snandasena** [tharindupr/BaiCoin#4]
Hi,

This will be a great initiative. Please add discussion support for this repo.

**Comment by snandasena** [comment]
Requesting to add GitHub discussion support for this repo.

**Comment by KingAlawaka** [comment]
bUbtiCpStBeGM7oB9DAcyAdqQ1QP9HJ7Vf

**Comment by tharindupr** [comment]
Thanks for the suggestion. Will add discussions soon.
